import { Geist, Geist_Mono } from "next/font/google";
import { Poppins, Inter } from 'next/font/google';
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['600', '700', '800'], 
  variable: '--font-poppins', 
});


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'], 
  variable: '--font-inter', 
});

export const metadata = {
  title: "EDMERCY Foundation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable}`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
